# Generated by Django 5.0.3 on 2024-03-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('karnali', 'karnali'), ('Sudurpashchim', 'Sudurpashchim'), ('Lumbini', 'Lumbini'), ('Gandaki', 'Gandaki'), ('Bagmati', 'Bagmati'), ('Madhesh', 'Madhesh'), ('Koshi', 'Koshi')], max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('docfile', models.FileField(blank=True, upload_to='docfile')),
            ],
        ),
    ]
